version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 5050:5050