version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 6060:6060