version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
