"""Users table: fullname now nullable.

Revision ID: 0d6f90be77c0
Revises: d023207f529e
Create Date: 2023-02-16 21:08:34.462556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6f90be77c0'
down_revision = 'd023207f529e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
