"""empty message

Revision ID: 120fb94cf350
Revises: ea749a392e0c
Create Date: 2023-02-28 13:50:32.460215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120fb94cf350'
down_revision = 'ea749a392e0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
