"""empty message

Revision ID: 1b951aeca425
Revises: 120fb94cf350
Create Date: 2023-02-28 13:51:13.325869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b951aeca425'
down_revision = '120fb94cf350'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
