"""empty message

Revision ID: 4b0d714256ac
Revises: 1b951aeca425
Create Date: 2023-02-28 13:52:07.084360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0d714256ac'
down_revision = '1b951aeca425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
