"""empty message

Revision ID: 501c48062f71
Revises: 4b0d714256ac
Create Date: 2023-02-28 13:52:26.175992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501c48062f71'
down_revision = '4b0d714256ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
