"""empty message

Revision ID: 714225f642aa
Revises: f6a3d4e34379
Create Date: 2023-02-28 13:50:11.415404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714225f642aa'
down_revision = 'f6a3d4e34379'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
