"""empty message

Revision ID: 9a622e572f0a
Revises: b2db016d71ff
Create Date: 2023-02-28 13:40:40.506199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a622e572f0a'
down_revision = 'b2db016d71ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
