"""empty message

Revision ID: b267b51514b6
Revises: 9a622e572f0a
Create Date: 2023-02-28 13:42:06.390444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b267b51514b6'
down_revision = '9a622e572f0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
