"""empty message

Revision ID: b2db016d71ff
Revises: d9be4c5f8a02
Create Date: 2023-02-26 02:12:40.492543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2db016d71ff'
down_revision = 'd9be4c5f8a02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variety', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('variety', 'decription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variety', sa.Column('decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('variety', 'description')
    # ### end Alembic commands ###
